[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fed-phish-guard"
version = "1.0.0"
description = "Federated Learning for Phishing URL Detection"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.26.1",
    "flwr-datasets>=0.6.0",
    "torch==2.8.0",
    "datasets==3.5.0",
    "numpy==2.2.4",
    "scikit-learn==1.8.0",
    "pandas==3.0.1",
    "tqdm==4.67.3",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "mozilla-ai"

[tool.flwr.app.components]
serverapp = "phishguard.server_app:app"
clientapp = "phishguard.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 2 # Number of federated learning rounds
fraction-train = 0.5 # Fraction of clients used for training in each round
fraction-evaluate = 0.5 # Fraction of clients used for evaluation in each round
local-epochs = 1 # Number of local epochs for each client
learning-rate = 1e-3
batch-size = 128
dataset-fraction = 0.2  # Fraction of each partition to use (1.0 = full dataset)
embed-dim = 64
num-filters = 128
dropout = 0.3
datasets = "ealvaradob/phishing-dataset"  # Comma-separated list of dataset IDs
